site_name: wltr-phonetics
site_url: https://github.com/walteravelino/wltr-phonetics
site_description: Wltr Phonetics é uma biblioteca de algoritmos fonéticos.
site_author: MkDocs Team

nav:
    - Instalação: index.md
    - Guia de uso: guia-de-uso.md
    - Sobre: sobre.md
    - Licença: licenca.md

repo_url: https://github.com/walteravelino/wltr-phonetics

theme: readthedocs
